name: "external-val"
version: "0.0.4"
usage: "get values from an external source"
description: "get values from an external source"
useTunnel: false
downloaders:
  - command: ./bin/helm-external-val downloader dummy
    protocols:
      - "cm"
      - "secret"
hooks:
  install: "$HELM_PLUGIN_DIR/scripts/install.sh"
